### ISSUE TITLE
Integration with Mojob

### ISSUE THREAD

**Issue by maszhin** [navikt/pam-annonsemottak#45]
Hi,

I'm representing Mojob AS, the fast-growing Norwegian startup in the recruitment industry. 
Is there any chance for us to integrate with your API? 

I see you support XML feed. Would it be possible for you to start crawling our listings?

**Comment by maszhin** [comment]
Here https://job.mojob.io/2496/ you can find an example of ad posted with Mojob

**Comment by maszhin** [comment]
@einarbj (I'm sorry for annotating you). 

We're struggling to contact NAV and get relevant information. Could you do us a favour and contact us with a person responsible for integrations?

**Comment by maszhin** [comment]
What standard do you support for feeding your XML crawler?

**Comment by einarbj** [comment]
Hello @maszhin

We do crawls to collect ads from some sources. To set up a crawler I will need to get back to you

**Comment by maszhin** [comment]
Hi,

Awesome. We could support you in integrating crawler with Mojob. 

> get back to you
Would you like to set up a video conference for setting up crawler? Or we need the management decision first?

**Comment by maszhin** [comment]
Hi Einar,

Could you tell us, how long it will take to integrate with your service? We're in the middle of the sprint and would like to estimate the deadline.

Let us know if we can somehow help you.

**Comment by einarbj** [comment]
As we'll need to get this into our queue as well, any further planning is done directly between our product owner and the developer that will implement the change. We'll keep this issue open until it is implemented 
CC: @bjornarne

**Comment by maszhin** [comment]
Thanks @einarbj.

Here you can find the implementation of our feed: https://api.mojob.io/feed/nav/
Currently not many jobs there (we released the service few days ago)

**Comment by tuantrannav** [comment]
closing this one, not really an issue
